### ISSUE TITLE
Add CVPR 2019 De Lange [Catastrophic Forgetting]  

### ISSUE THREAD

**Issue by rokity** [ContinualAI/continual-learning-papers#14]
`@article{Delange_2021,
	doi = {10.1109/tpami.2021.3057446},
	url = {https://doi.org/10.1109%2Ftpami.2021.3057446},
	year = 2021,
	publisher = {Institute of Electrical and Electronics Engineers ({IEEE})},
	pages = {1--1},
	author = {Matthias Delange and Rahaf Aljundi and Marc Masana and Sarah Parisot and Xu Jia and Ales Leonardis and Greg Slabaugh and Tinne Tuytelaars},
	title = {A continual learning survey: Defying forgetting in classification tasks},
	journal = {{IEEE} Transactions on Pattern Analysis and Machine Intelligence}
}`

**Comment by AndreaCossu** [comment]
We already have this :smile: Under `Review Papers and Books` section

**Comment by rokity** [comment]
My mistake sorry.
